- Assets/Prefabs/Arrow.prefab
- Assets/Prefabs/Arrow.prefab.meta
- Assets/Prefabs/Player.prefab
- Assets/Scripts/Arrow.cs
- Assets/Scripts/Arrow.cs.meta
- Assets/Scripts/PlayerController.cs
- ProjectSettings/InputManager.asset
- ProjectSettings/QualitySettings.asset
- ProjectSettings/UnityConnectSettings.asset
Added arrows that
- Kill when contacts player in air
- Adds to a counter when contact player when grounded
- Sticks to the environment when collides with it
> Added arrows

- Assets/Prefabs/Player.prefab
- Assets/Scripts/FallState.cs
- Assets/Scripts/IdleState.cs
- Assets/Scripts/InputActionMapper.cs
- Assets/Scripts/InputActionMapper.cs.meta
- Assets/Scripts/JumpState.cs
- Assets/Scripts/PlayerController.cs
- Assets/Scripts/RopeSystem.cs
- Assets/Scripts/RunState.cs
Created input action mapper to encapsulate input details and have cleaner interface for player class
> Action mapper

- Assets/Scenes/EndGame.unity
- Assets/Scenes/EndGame.unity.meta
- Assets/Scenes/Main.unity
- Assets/Scripts/EndGame.cs
- Assets/Scripts/EndGame.cs.meta
- Assets/Scripts/Match.cs
- Assets/Scripts/Match.cs.meta
- Assets/Scripts/PlayerController.cs
- ProjectSettings/EditorBuildSettings.asset
- ProjectSettings/UnityConnectSettings.asset
Adds a scene that says Game Over when there's 1 player remaining and an option to go back to the Main Menu
> Added End Game screen

- Assets/Scripts/PlayerController.cs
while being pulled by the grappling hook or at the end state, press jump to go into fall
> jump to get out of hook

- Assets/Scripts/InputActionMapper.cs
stick up would pass deadzone, but slight left/ right would still trigger as horizontal input
> added lower bound for what is considered horizontal input

- Assets/Prefabs/MSCharacter.prefab
- Assets/Scripts/PlayerController.cs
flip character transform scale based on directional input instead of flipping sprites
> update how Facing works

- Assets/Prefabs/Arrow.prefab
- Assets/Prefabs/MSCharacter.prefab
- Assets/Scenes/Main.unity
- Assets/Scripts/Arrow.cs
- Assets/Scripts/PlayerController.cs
- ProjectSettings/Physics2DSettings.asset
- ProjectSettings/TagManager.asset
- ProjectSettings/TimeManager.asset
Fixes a lot of physics things. Everything actually works how one would expect it to work in a 2D game. Arrows no longer kill the player that fired them. There are a few changes I made to the colliders on the prefabs to smooth things out.
> Fix bugs with falling through platform and projectile collisions.

- Assets/Input/Goose Game Actions.inputactions
- Packages/manifest.json
Also updated input system package to the newest version, so you might have to update your package under Window->Package Manager->Input System
> Fix switch submit

- Assets/Scripts/GameManager.cs
- Assets/Scripts/PlayerManager.cs
This reverts commit 7fe998c6b27216688691bdd66c2cd4d15521b8e8.
turns out keyboard is actually disadvantaged and real hard to aim
> Revert "Hides cursor during game"

- Assets/Scripts/PlayerController.cs
> Fix Jump SFX

- Assets/Prefabs/MSCharacter.prefab
- Assets/Scripts/PlayerController.cs
- increase size of wall jump checks
- make sure player ui doesn't flip when character does
> Wall jump checks + player ui flip

- Assets/Prefabs/PlayerSelection.prefab
- Assets/Scenes/PlayerSelection.unity
- Assets/Scripts/GameLobbyPlayer.cs
- Assets/Scripts/PlayerManager.cs
- added back navigation indicator with progress bar
- added fight prompt to start game when enough players are ready
> player select UI improvements

- Assets/Scripts/GameManager.cs
- Assets/Scripts/PlayerController.cs
everyone's alive variable was true, so only p1 was 'winning'
> endgame screen wasn't actually showing who won

- Assets/Prefabs/OGCharacter.prefab
- Assets/Scenes/Main.unity
> shrunk map a bit

- Assets/Scripts/PlayerController.cs
- up, forward, and down animations
> use attack animations for shooting shuriken

- Assets/Scenes/Main.unity
- added decorations to background sorting layer so that any game particles/ sprites render on top
> cleaned up decoration + background render layer sort

- Assets/Scripts/GameManager.cs
- made it shake on every player death
- slow down time when the last player dies
> added more oomph to player deaths and final player death

- Assets/Scenes/Main.unity
- Assets/Scripts/GameManager.cs
> added banner bg for countdown

- Assets/Auto Letterbox.meta
- Assets/Auto Letterbox/Documentation.meta
- Assets/Auto Letterbox/Editor.meta
- Assets/Auto Letterbox/Editor/ForceCameraRatioEditor.cs
- Assets/Auto Letterbox/Editor/ForceCameraRatioEditor.cs.meta
- Assets/Auto Letterbox/ForceCameraRatio.cs
- Assets/Auto Letterbox/ForceCameraRatio.cs.meta
- Assets/Scenes/Main.unity
- added asset to force aspect ratio of in-game screen
https://assetstore.unity.com/packages/tools/camera/auto-letterbox-56814
> fit on multiple aspect ratios

- Assets/Prefabs/OGCharacter.prefab
- Assets/Scripts/PlayerController.cs
- move hook end state force facing to update rather than start
- set Facing on setting ForceFacing
> changed forceFacing at hook end state

- Assets/Scripts/GrapplingHook.cs
Hook no longer latches when returning
> Only latch hook when shooting

- Assets/Prefabs/OGCharacter.prefab
- Assets/Scripts/PlayerController.cs
- Assets/Water Hero 1/Original/FX/weapon on wall/star weapon.png.meta
> Icon star count label

- Assets/Input/Goose Game Actions.inputactions
- Assets/Prefabs/OGCharacter.prefab
- Assets/Scenes/MainMenu.unity
- Assets/Scenes/Tutorial.unity
- Assets/Scenes/Tutorial.unity.meta
- Assets/Scripts/MainMenu.cs
- Assets/Scripts/PlayerController.cs
- Assets/Scripts/PlayerManager.cs
- Assets/Scripts/Tutorial.cs
- Assets/Scripts/Tutorial.cs.meta
- ProjectSettings/EditorBuildSettings.asset
- note: haven't added instructions about arrow redirect cause i like dash better, but it's not ready
> added tutorial

- Assets/Animations/OGCharacter/Player.controller
- Assets/Scripts/PlayerController.cs
- makes no sense to be grappled to the ground beneath you, so just go to idle
> go to idle when player grapples down

- Assets/Input/Goose Game Actions.inputactions
- Assets/Prefabs/GameLobbyPlayer.prefab
- Assets/Scenes/MainMenu.unity
- Assets/Scenes/PlayerSelection.unity
- Packages/manifest.json
super unintuitive not to be able to click on buttons
- now we can
> allow clicking on menu UI items

- Assets/Prefabs/LivesUI.prefab
- Assets/Prefabs/LivesUI.prefab.meta
- Assets/Scenes/Main.unity
- Assets/Scripts/GameManager.cs
- Assets/Scripts/LivesHUD.cs
- Assets/Scripts/LivesHUD.cs.meta
- Assets/Scripts/PlayerController.cs
- Assets/Scripts/PlayerManager.cs
- `PlayerController` depended on lives textmeshpro instance, but tutorial doesn't have that
- refactored lives ui to depend on `PlayerController` and remove dependency from `PlayerController`
> refactored Lives ui to prevent tutorial bug

- Assets/Input/Goose Game Actions.inputactions
- Assets/Scenes/Tutorial.unity
- Assets/Scripts/InputActionMapper.cs
- Assets/Scripts/PlayerController.cs
- updated tutorial
- changed controls:
- Keyboard:
- shift to dash
- E to grappling hook
- left click to melee
- right click for shoot shuriken
- Gamepad:
- east button to dash
> updated tutorial with dash and changed controls

- Assets/Prefabs/OGCharacter.prefab
- when standing still, melee attacks didn't always trigger due to static colliders
- added kinematic rigidbody to melee to improve static collision
> added kinematic rigidbody to melee for better detection

- Assets/Scripts/PlayerController.cs
Fixes bug where arrows get stuck in wall when shooting from corner
> Adjust arrow start dist

- Assets/Scripts/PlayerController.cs
Make wall jump jump more so it feels you actually jumping off of a wall.
> Adjust wall jump

- Assets/Prefabs/Dummy.prefab
- Assets/Prefabs/Dummy.prefab.meta
- Assets/Scenes/Tutorial.unity
- Assets/Scripts/DummyController.cs
- Assets/Scripts/DummyController.cs.meta
- Assets/Scripts/Melee.cs
- Assets/Scripts/Tutorial.cs
> added dummy to tutorial

- Assets/Prefabs/Dummy.prefab
- Assets/Scenes/Tutorial.unity
- Assets/Scripts/Arrow.cs
- ProjectSettings/GraphicsSettings.asset
Allow dummy to be killed by stars
Resize tutorial canvas 
Rename dummy label
> Tutorial enhancements
